  - alias: 'Abends alle Außenlichter an'
    trigger:
      - platform: sun
        event: sunset
    action:
      service: light.turn_on
      data:
        entity_id:
          - light.licht_aussen_dachkasten
          - light.licht_aussen_hausnummer
  - alias: 'Dachkasten aus um 23:00 Uhr'
    trigger:
      - platform: time
        at: "23:00:00"
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.licht_aussen_dachkasten
  - alias: 'Morgens Hausnummer aus'
    trigger:
      - platform: sun
        event: sunrise
        offset: '-01:00:00'
    action:
      service: light.turn_off
      data:
        entity_id:
          - light.licht_aussen_hausnummer
  - alias: 'OG Bad Lüfter: Timer bei Bewegung einschalten'
    trigger:
      - platform: state
        entity_id: binary_sensor.og_bad_prasenzmelder_bewegung
        to: "on"
    action:
      service: timer.start
      data:
        entity_id:
          - timer.og_luefter_bad_einschalten
  - alias: 'OG Bad Lüfter bei Timer einschalten'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.og_luefter_bad_einschalten
    action:
      service: switch.turn_on
      data:
        entity_id:
          - switch.og_bad_lufter
  - alias: 'OG Bad Lüfter nach 10 min ausschalten'
    trigger:
      - platform: state
        entity_id: binary_sensor.og_bad_prasenzmelder_bewegung
        to: "off"
        for:
          minutes: 10
    action:
      service: switch.turn_off
      data:
        entity_id:
          - switch.og_bad_lufter
  - alias: 'Zirkulationspumpe an'
    trigger:
      - platform: time_pattern
        minutes: "/5"
    condition:
      - condition: or
        conditions:
          - condition: time
            after: '07:00:00'
            before: '08:00:00'
          - condition: time
            after: '19:00:00'
            before: '21:00:00'
      - condition: state
        entity_id: switch.heizung_zirkulationspumpe
        state: 'off'
        for:
          minutes: 15
    action:
      service: switch.turn_on
      data:
        entity_id:
          - switch.heizung_zirkulationspumpe
  - alias: 'Zirkulationspumpe aus'
    trigger:
      - platform: time_pattern
        minutes: "/5"
    condition:
      condition: state
      entity_id: switch.heizung_zirkulationspumpe
      state: 'on'
      for:
        minutes: 15
    action:
      service: switch.turn_off
      data:
        entity_id:
          - switch.heizung_zirkulationspumpe
  - alias: 'Abends Rolläden im SZ runterfahren'
    trigger:
      - platform: sun
        event: sunset
    action:
      service: cover.close_cover
      data:
        entity_id:
          - cover.og_sz
  - alias: 'Alarm (wenn Außer Haus) auslösen'
    trigger:
      - platform: state
        entity_id: binary_sensor.og_bad_prasenzmelder_bewegung
        to: 'on'
      - platform: state
        entity_id: binary_sensor.eg_flur_prasenzmelder_bewegung
        to: 'on'
      - platform: state
        entity_id: binary_sensor.eg_esszimmer_fenster_zu
        to: 'off'
      - platform: state
        entity_id: binary_sensor.eg_esszimmer_aussentur_zu
        to: 'off'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmanlage
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarmanlage
  - alias: 'Alarm (wenn zu Hause) auslösen'
    trigger:
      - platform: state
        entity_id: binary_sensor.eg_esszimmer_fenster_zu
        to: 'off'
      - platform: state
        entity_id: binary_sensor.eg_esszimmer_aussentur_zu
        to: 'off'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarmanlage
        state: armed_home
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarmanlage
  - alias: 'Alarm melden'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmanlage
        to: 'triggered'
    action:
      - service: notify.pushbullet
        data:
          message: "ALARM! Es tut sich was im Haus!"
      - service: notify.xmpp
        data:
          message: "ALARM! Es tut sich was im Haus!"
  - alias: 'Rolläden Status fix'
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: '00:00:20'
      - service: cover.stop_cover
        entity_id:
          - cover.og_sz_balkontur
          - cover.og_sz_fenster
