---
default_config:

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info
  logs:
    homeassistant.components.unifi: debug
    homeassistant.components.device_tracker.unifi: debug
        
homeassistant:
  name: "Home Sweet Home"
  elevation: 1
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: Europe/Berlin
  temperature_unit: C
  customize:
    person.fabian:
      entity_picture: /local/bit_gross.jpg
      icon: /local/bit_gross.jpg
    switch.sperre_licht_alle_flure:
      assumed_state: true
    switch.sperre_licht_og_badezimmer:
      assumed_state: true

zone: !include zones.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automation/

# Datenbank
recorder:
  db_url: "postgresql://@/homeassistant"
  purge_keep_days: 14

history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - timer
      - device_tracker
      - zone
      - sun
      - alert
      - notify
    entities:
      - binary_sensor.eg_esszimmer_aussentur_zu_invertiert
      - binary_sensor.eg_esszimmer_fenster_zu_invertiert
      - binary_sensor.updater
      - cover.og_sz
      - sensor.nextsunrise
      - sensor.nextsunset

prometheus:
  namespace: "ha"
  filter:
    include_entities:
      - sensor.eg_flur_prasenzmelder_helligkeit
      - sensor.eg_flur_prasenzmelder_temperatur
      - sensor.og_flur_prasenzmelder_helligkeit
      - sensor.og_flur_prasenzmelder_temperatur
      - sensor.og_bad_prasenzmelder_helligkeit
      - sensor.og_bad_prasenzmelder_luftfeuchtigkeit
      - sensor.og_bad_prasenzmelder_temperatur
    include_entity_globs:
      - sensor.heizkessel*
  component_config_glob:
    sensor.*helligkeit:
      override_metric: illuminance
    sensor.*temperatur:
      override_metric: temperature
    sensor.*luftfeuchtigkeit:
      override_metric: humidity
    sensor.heizkessel_energieverbrauch_gas*:
      override_metric: active_energy_kwh_gas
    sensor.heizkessel_energieverbrauch_strom*:
      override_metric: active_energy_kwh_power

alarm_control_panel:
  - platform: manual
    name: Alarmanlage
    arming_time: 20

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily
    name: Wetter

knx: !include knx/knx.yaml

mqtt:
  broker: 127.0.0.1

device_tracker: !include device_tracker.yaml

utility_meter:
  meter_heating:
    source: sensor.heizkessel_energieverbrauch_gas_fur_heizung
    cycle: yearly
  meter_heating_water:
    source: sensor.heizkessel_energieverbrauch_gas_fur_warmwasser
    cycle: yearly

sensor: !include entities/sensor.yaml
binary_sensor: !include entities/binary_sensor.yaml
input_boolean: !include entities/boolean.yaml
timer: !include entities/timer.yaml
cover: !include entities/cover.yaml
notify: !include entities/notify.yaml
