---
tunneling:
  host: '10.42.0.13'
  port: 3671
  local_ip: '10.42.0.3'
fire_event: true
fire_event_filter: ["*/*/*"]
switch:
  - name: "OG Bad Lüfter"
    address: "2/0/5"
    state_address: "2/1/5"
  - name: "Heizung Zirkulationspumpe"
    address: "2/0/9"
    state_address: "2/1/9"
  - name: "Sperre Licht OG Badezimmer"
    address: "0/2/15"
  - name: "Sperre Licht Alle Flure"
    address: "0/2/11"
light:
  - name: "Licht EG HWR"
    address: "0/0/2"
    state_address: "0/1/2"
  - name: "Licht EG Gäste-WC"
    address: "0/0/3"
    state_address: "0/1/3"
  - name: "Licht EG Windfang"
    address: "0/0/4"
    state_address: "0/1/4"
  - name: "Licht EG Wohnzimmer Sofa"
    address: "0/0/5"
    state_address: "0/1/5"
  - name: "Licht EG Wohnzimmer Durchgang"
    address: "0/0/6"
    state_address: "0/1/6"
  - name: "Licht EG HWR Fenster"
    address: "0/0/7"
    state_address: "0/1/7"
  - name: "Licht EG Esszimmer Theke"
    address: "0/0/8"
    state_address: "0/1/8"
  - name: "Licht EG Esszimmer Steinwand"
    address: "0/0/9"
    state_address: "0/1/9"
  - name: "Licht EG Esszimmer Terrasse"
    address: "0/0/10"
    state_address: "0/1/10"
  - name: "Licht EG Flur"
    address: "0/0/11"
    state_address: "0/1/11"
  - name: "Licht EG Wohnzimmer LED-Stripe"
    address: "0/0/12"
    state_address: "0/1/12"
  - name: "Licht Außen Hausnummer"
    address: "0/0/13"
    state_address: "0/1/13"
  - name: "Licht Außen Dachkasten"
    address: "0/0/14"
    state_address: "0/1/14"
  - name: "Licht OG Badezimmer"
    address: "0/0/15"
    state_address: "0/1/15"
  - name: "Licht OG Schlafzimmer 1"
    address: "0/0/16"
    state_address: "0/1/16"
  - name: "Licht OG Schlafzimmer 2"
    address: "0/0/17"
    state_address: "0/1/17"
  - name: "Licht OG Schlafzimmer 3"
    address: "0/0/18"
    state_address: "0/1/18"
  - name: "Licht Dachboden"
    address: "0/0/19"
    state_address: "0/1/19"
  - name: "Licht OG Flur Wand"
    address: "0/0/20"
    state_address: "0/1/20"
  - name: "Licht OG Atelier"
    address: "0/0/22"
    state_address: "0/1/22"
  - name: "Licht OG Atelier"
    address: "0/0/22"
    state_address: "0/1/22"
  - name: "Licht OG Gästezimmer"
    address: "0/0/23"
    state_address: "0/1/23"
  - name: "Licht OG Arbeitszimmer"
    address: "0/0/24"
    state_address: "0/1/24"
cover:
  - name: "OG SZ Fenster"
    move_long_address: '3/0/0'
    move_short_address: '3/0/1'
    travelling_time_down: 18
    travelling_time_up: 18
  - name: "OG SZ Balkontür"
    move_long_address: '3/0/2'
    move_short_address: '3/0/3'
    travelling_time_down: 25
    travelling_time_up: 25
binary_sensor:
  - name: "EG Flur Präsenzmelder Bewegung"
    state_address: "2/2/0"
    device_class: motion
  - name: "OG Bad Präsenzmelder Bewegung"
    state_address: "2/2/1"
    device_class: motion
  - name: "OG Flur Präsenzmelder Bewegung"
    state_address: "2/2/2"
    device_class: motion
  - name: "EG Esszimmer Fenster zu invertiert"
    state_address: "1/1/6"
  - name: "EG Esszimmer Aussentür zu invertiert"
    state_address: "1/1/7"
  - name: "Heizkessel Wartungsmodus"
    state_address: "1/0/0"
    sync_state: 1
  - name: "Heizkessel Fehler Wärmeerzeuger"
    state_address: "1/0/1"
    sync_state: 1
  - name: "Heizkessel Systemstatus Standby"
    state_address: "1/0/3"
    sync_state: 1
  - name: "Heizkessel Systemstatus Heizen"
    state_address: "1/0/4"
    sync_state: 1
  - name: "Heizkessel Systemstatus Warmwasser"
    state_address: "1/0/5"
    sync_state: 1
sensor:
  - name: "EG Flur Präsenzmelder Helligkeit"
    state_address: "2/1/1"
    type: "illuminance"
  - name: "EG Flur Präsenzmelder Temperatur"
    state_address: "2/1/2"
    type: "temperature"
  - name: "OG Flur Präsenzmelder Helligkeit"
    state_address: "2/1/3"
    type: "illuminance"
  - name: "OG Flur Präsenzmelder Temperatur"
    state_address: "2/1/4"
    type: "temperature"
  - name: "OG Bad Präsenzmelder Helligkeit"
    state_address: "2/1/6"
    type: "illuminance"
  - name: "OG Bad Präsenzmelder Temperatur"
    state_address: "2/1/7"
    type: "temperature"
  - name: "OG Bad Präsenzmelder Luftfeuchtigkeit"
    state_address: "2/1/8"
    type: "humidity"
  - name: "Heizkessel Außentemperatur"
    state_address: "1/0/2"
    sync_state: "every 1"
    type: "temperature"
  - name: "Heizkessel Wasserdruck"
    state_address: "1/0/6"
    sync_state: "every 1"
    type: "pressure_2byte"
  - name: "Heizkessel Warmwasserkreis Sollwert Warmwasser"
    state_address: "1/0/10"
    sync_state: "every 1"
    type: "temperature"
  - name: "Heizkessel Warmwasserkreis Wassertemperatur"
    state_address: "1/0/12"
    sync_state: "every 1"
    type: "temperature"
  - name: "Heizkessel Energieverbrauch Gas für Heizung"
    state_address: "1/0/13"
    sync_state: every 1
    type: "active_energy_kwh"
  - name: "Heizkessel Energieverbrauch Gas für Warmwasser"
    state_address: "1/0/14"
    sync_state: every 1
    type: "active_energy_kwh"
  - name: "Heizkessel Energieverbrauch Strom für Heizung"
    state_address: "1/0/15"
    sync_state: every 1
    type: "active_energy_kwh"
  - name: "Heizkessel Energieverbrauch Strom für Warmwasser"
    state_address: "1/0/16"
    sync_state: every 1
    type: "active_energy_kwh"
  - name: "Heizkessel Zone 1 Tagtemperatur"
    state_address: "1/0/18"
    sync_state: "every 1"
    type: "temperature"
  - name: "Heizkessel Zone 1 Nachttemperatur"
    state_address: "1/0/19"
    sync_state: "every 1"
    type: "temperature"
  - name: "Heizkessel Vorlauftemperatur"
    state_address: "1/0/20"
    sync_state: "every 1"
    type: "temperature"
  - name: "Heizkessel Heizkurve"
    state_address: "1/0/21"
    sync_state: "every 1"
    type: "DPT-9"
